package service;

import dto.LoginDTO;
import helper.security.Authentication;
import helper.security.Confidentiality;
import model.User;
import repository.UserRepository;

import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.Socket;
import java.security.PublicKey;
import java.util.Arrays;

public class AuthServiceImpl implements AuthService {

    private final UserRepository userRepository;
    private final Socket socket;

    public AuthServiceImpl(UserRepository userRepository, Socket socket) {
        this.userRepository = userRepository;
        this.socket = socket;
    }

    @Override
    public void login(String username, String password) {

        try {
            var user = userRepository.getUser(username);
            var salt = new byte[256];

            if (user.isPresent()) {
                salt = user.get().getPasswordSalt();
            } else {
                System.out.println("User not found");
                return;
            }

            // FIXME: encrypt the pword with server's public key hash it on the server side

            byte[] passwordHash = Authentication.hashPassword(password, salt);
            LoginDTO loginDTO = new LoginDTO(username, passwordHash);
            DataOutputStream out = new DataOutputStream(socket.getOutputStream());

            String nonce = Authentication.generateNonce();

            var privateKey = userRepository.getPrivateKey(username);

            var signedMessage = Authentication.sign(nonce.getBytes(), privateKey.orElseThrow());

            String loginMessagePayload = "LOGIN" + " " + loginDTO.getLoginString() + " "
                    + Arrays.toString(signedMessage);

            //String loginMessage = Authentication.appendMACToMessage();

            //out.writeUTF(loginMessage);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void register(String username, String password) {
        try {
            DataOutputStream out = new DataOutputStream(socket.getOutputStream());
            DataInputStream in = new DataInputStream(new BufferedInputStream(socket.getInputStream()));

            String helloMsg = "HELLO";
            out.writeUTF(helloMsg);

            System.out.println("message received by client: " + in.readUTF());

            User user = new User(username, password);

            PublicKey publicKey = user.getKeyPair().getPublic();

            // wait for server to respond with its public key

            while (true){
                String[] serverResponse = in.readUTF().split(" ");
                if (serverResponse[0].equals("PUBLICKEY")) {
                    user.getUserStorage().setServerPublicKey(serverResponse[1].getBytes());
                    break;
                }
            }


            PublicKey serverPublicKey = Confidentiality.getPublicKeyFromByteArray(user.getUserStorage().getServerPublicKey());

            // send MAC key to server
            byte[] macKey = Authentication.generateMACKey();
            String macKeyString = "MAC" + " " + "Secretmsg123!" + " " + Arrays.toString(macKey);
            byte[] encryptedMacKey = Confidentiality.encryptWithPublicKey(macKeyString.getBytes(), serverPublicKey);
            System.out.println("MAC generated by client: " + Arrays.toString(Authentication.generateMAC("Secretmsg123!".getBytes(), macKey)));

            out.writeUTF(Arrays.toString(encryptedMacKey));

            /*
            String _registerMessagePayload
                    = "REGISTER" + " " + username + " " + password
                    + " " + Arrays.toString(user.getPasswordSalt())
                    + " " + publicKey.toString();

            String registerMessagePayload = Authentication.appendMACToMessage(_registerMessagePayload.getBytes(), MAC);

            // FIXME: maybe add nonce to avoid replay attacks

            // encrypt the message with the server's public key
            byte[] encryptedMessage = Confidentiality.encryptWithSymmetricKey(registerMessagePayload.getBytes(), serverPublicKey);

            // send the encrypted message to the server
            out.writeUTF(Arrays.toString(encryptedMessage));

*/

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void logout() {

    }
}
