import com.sun.net.httpserver.HttpServer;
import frontend.MyHTTPServer;
import helper.security.Authentication;
import helper.security.Confidentiality;
import model.Server;

import java.io.IOException;
import java.net.BindException;
import java.net.InetSocketAddress;
import java.security.NoSuchAlgorithmException;
import java.security.PublicKey;
import java.util.Arrays;

public class Main {
    public static void main(String[] args) throws Exception {

        new Thread(() -> {
            try {
                HttpServer server1 = HttpServer.create(new InetSocketAddress(8000), 0);
                MyHTTPServer myServer1 = new MyHTTPServer(server1);
                myServer1.startHttpServer();
            } catch (IOException e) {
                e.printStackTrace();
                System.out.println("Error starting HTTP Server");
            }
        }).start();

        new Thread(() -> {
            try {
                HttpServer server2 = HttpServer.create(new InetSocketAddress(8001), 0);
                MyHTTPServer myServer2 = new MyHTTPServer(server2);
                myServer2.startHttpServer();
            } catch (IOException e) {
                e.printStackTrace();
                System.out.println("Error starting HTTP Server");
            }
        }).start();

        new Thread(() -> {
            try {
                HttpServer server3 = HttpServer.create(new InetSocketAddress(8002), 0);
                MyHTTPServer myServer3 = new MyHTTPServer(server3);
                myServer3.startHttpServer();
            } catch (IOException e) {
                e.printStackTrace();
                System.out.println("Error starting HTTP Server");
            }
        }).start();

        ApplicationManager.getInstance().run();

    /*
        Server server = Server.getInstance(1233);
        byte[] macKey = Authentication.generateMACKey();
        PublicKey serverPublicKey = Confidentiality.getPublicKeyFromByteArray(Confidentiality.getByteArrayFromPublicKey(server.getPublicKey()));
        byte[] encryptedMacKey = Confidentiality.encryptWithPublicKey(macKey, serverPublicKey);
        String macKeyString = "MAC" + " " + "Secretmsg123!" + Arrays.toString(encryptedMacKey);
        // mackey
        System.out.println("MAC key: " + Arrays.toString(macKey));
        System.out.println("Encrypted: " + Arrays.toString(encryptedMacKey));
        System.out.println("MAC generated by client: " + Arrays.toString(Authentication.generateMAC("Secretmsg123!".getBytes(), macKey)));

        byte[] decrypted = Confidentiality.decryptWithPrivateKey(encryptedMacKey, Confidentiality.getPrivateKeyFromByteArray(Confidentiality.getByteArrayFromPrivateKey(server.getKeyPair().getPrivate())));
        System.out.println("Decrypted: " + Arrays.toString(decrypted));
        System.out.println("MAC generated by server: " + Arrays.toString(Authentication.generateMAC("Secretmsg123!".getBytes(), macKey)));


     */

    }
}